language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --prefer-dist --dev install
  - cp phpunit.xml.dist phpunit.xml
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit -c ./
